version: '3.9'

services:
  fe:
    build:
      context: Frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '3000:3000'
  be:
    build:
      context: Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8888:8888'

volumes:
  db-data: {}
